// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.28.0";

// src/lib/mcp/tools/list-actions.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.28.0";
import { z } from "npm:zod@^3.25.76";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.100.0";
function runtimeEnv(name) {
  const runtime = globalThis;
  return runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
}
function configuredEnv(names) {
  for (const name of names) {
    const value = runtimeEnv(name)?.trim();
    if (value) return value;
  }
  return void 0;
}
function supabaseProjectUrl() {
  const url = configuredEnv(["SUPABASE_URL", "VITE_SUPABASE_URL"]);
  if (!url) throw new Error("SUPABASE_URL (or VITE_SUPABASE_URL) is required");
  return url;
}
function supabasePublishableKey() {
  const direct = configuredEnv([
    "SUPABASE_PUBLISHABLE_KEY",
    "VITE_SUPABASE_PUBLISHABLE_KEY"
  ]);
  if (direct) return direct;
  const keyset = runtimeEnv("SUPABASE_PUBLISHABLE_KEYS");
  if (keyset) {
    try {
      const parsed = JSON.parse(keyset);
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
        const keys = parsed;
        const key = [keys.default, ...Object.values(keys)].find((v) => typeof v === "string" && v.trim().startsWith("sb_publishable_"))?.trim();
        if (key) return key;
      }
    } catch {
    }
  }
  const legacy = configuredEnv(["SUPABASE_ANON_KEY", "VITE_SUPABASE_ANON_KEY"]);
  if (legacy) return legacy;
  throw new Error("SUPABASE_PUBLISHABLE_KEY, SUPABASE_PUBLISHABLE_KEYS, or SUPABASE_ANON_KEY is required");
}
function supabaseForUser(ctx) {
  const token = ctx.getToken();
  if (!token) throw new Error("supabaseForUser requires a verified OAuth token");
  return createClient(supabaseProjectUrl(), supabasePublishableKey(), {
    global: { headers: { Authorization: `Bearer ${token}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
function notAuthenticated() {
  return {
    content: [{ type: "text", text: "N\xE3o autenticado. Conecte-se com sua conta do Politiza IA." }],
    isError: true
  };
}

// src/lib/mcp/tools/list-actions.ts
var list_actions_default = defineTool({
  name: "list_actions",
  title: "Listar a\xE7\xF5es de campo",
  description: "Lista a\xE7\xF5es de campo da campanha (t\xEDtulo, munic\xEDpio, status, data planejada/executada, p\xFAblico atingido), com filtros opcionais.",
  inputSchema: {
    candidate_id: z.string().uuid().optional().describe("Filtra por candidato."),
    municipality: z.string().trim().min(1).optional().describe("Filtra por munic\xEDpio (busca parcial)."),
    status: z.string().trim().min(1).optional().describe("Filtra por status exato (ex.: planejada, executada)."),
    since: z.string().optional().describe("Data m\xEDnima (YYYY-MM-DD) para planned_date."),
    limit: z.number().int().min(1).max(200).optional().describe("M\xE1ximo de registros (padr\xE3o 50).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ candidate_id, municipality, status, since, limit }, ctx) => {
    if (!ctx.isAuthenticated()) return notAuthenticated();
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("actions").select(
      "id,title,type,category,municipality,macroregion_id,status,priority,planned_date,executed_date,executed_people_count,estimated_impact,impact_score,responsible,candidate_id"
    ).is("deleted_at", null).order("planned_date", { ascending: false }).limit(limit ?? 50);
    if (candidate_id) query = query.eq("candidate_id", candidate_id);
    if (municipality) query = query.ilike("municipality", `%${municipality}%`);
    if (status) query = query.eq("status", status);
    if (since) query = query.gte("planned_date", since);
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { actions: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-candidates.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.28.0";
import { z as z2 } from "npm:zod@^3.25.76";
var list_candidates_default = defineTool2({
  name: "list_candidates",
  title: "Listar candidatos",
  description: "Lista os candidatos aos quais o usu\xE1rio conectado tem acesso (nome, partido, cargo, ano).",
  inputSchema: {
    only_active: z2.boolean().optional().describe("Se verdadeiro, retorna apenas candidatos ativos."),
    limit: z2.number().int().min(1).max(100).optional().describe("M\xE1ximo de registros (padr\xE3o 50).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ only_active, limit }, ctx) => {
    if (!ctx.isAuthenticated()) return notAuthenticated();
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("candidates").select("id,name,party,cargo,state,election_year,is_active").order("name").limit(limit ?? 50);
    if (only_active) query = query.eq("is_active", true);
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { candidates: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-leaders.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.28.0";
import { z as z3 } from "npm:zod@^3.25.76";
var list_leaders_default = defineTool3({
  name: "list_leaders",
  title: "Listar lideran\xE7as",
  description: "Lista lideran\xE7as municipais cadastradas (nome, munic\xEDpio, n\xEDvel de influ\xEAncia, alinhamento, apoiadores estimados).",
  inputSchema: {
    search: z3.string().trim().min(1).optional().describe("Busca parcial por nome."),
    municipality: z3.string().trim().min(1).optional().describe("Filtra por munic\xEDpio (busca parcial)."),
    candidate_id: z3.string().uuid().optional().describe("Filtra por candidato."),
    min_influence: z3.number().int().min(0).max(10).optional().describe("N\xEDvel m\xEDnimo de influ\xEAncia."),
    limit: z3.number().int().min(1).max(200).optional().describe("M\xE1ximo de registros (padr\xE3o 50).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ search, municipality, candidate_id, min_influence, limit }, ctx) => {
    if (!ctx.isAuthenticated()) return notAuthenticated();
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("leaders").select(
      "id,name,municipality,microregion,macroregion_id,influence_level,mobilization_capacity,estimated_supporters,alignment_status,support_status,current_party,candidate_id"
    ).is("deleted_at", null).order("influence_level", { ascending: false }).limit(limit ?? 50);
    if (search) query = query.ilike("name", `%${search}%`);
    if (municipality) query = query.ilike("municipality", `%${municipality}%`);
    if (candidate_id) query = query.eq("candidate_id", candidate_id);
    if (typeof min_influence === "number") query = query.gte("influence_level", min_influence);
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { leaders: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-political-assets.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.28.0";
import { z as z4 } from "npm:zod@^3.25.76";
var list_political_assets_default = defineTool4({
  name: "list_political_assets",
  title: "Listar ativos pol\xEDticos",
  description: "Lista ativos pol\xEDticos (prefeitos, vereadores, apoiadores e demais contatos estrat\xE9gicos) com munic\xEDpio, cargo e alinhamento.",
  inputSchema: {
    search: z4.string().trim().min(1).optional().describe("Busca parcial por nome."),
    municipality: z4.string().trim().min(1).optional().describe("Filtra por munic\xEDpio (busca parcial)."),
    candidate_id: z4.string().uuid().optional().describe("Filtra por candidato."),
    limit: z4.number().int().min(1).max(200).optional().describe("M\xE1ximo de registros (padr\xE3o 50).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ search, municipality, candidate_id, limit }, ctx) => {
    if (!ctx.isAuthenticated()) return notAuthenticated();
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("political_assets").select(
      "id,name,nickname,type,position,municipality,microregion,macroregion_id,influence_level,alignment_status,support_status,candidate_id"
    ).is("deleted_at", null).order("name").limit(limit ?? 50);
    if (search) query = query.ilike("name", `%${search}%`);
    if (municipality) query = query.ilike("municipality", `%${municipality}%`);
    if (candidate_id) query = query.eq("candidate_id", candidate_id);
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { assets: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-strategic-alerts.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.28.0";
import { z as z5 } from "npm:zod@^3.25.76";
var list_strategic_alerts_default = defineTool5({
  name: "list_strategic_alerts",
  title: "Listar alertas estrat\xE9gicos",
  description: "Lista alertas estrat\xE9gicos da Sala de Crise (risco/oportunidade por territ\xF3rio, severidade, recomenda\xE7\xE3o e status).",
  inputSchema: {
    status: z5.string().trim().min(1).optional().describe("Filtra por status exato (ex.: aberto, resolvido)."),
    municipality: z5.string().trim().min(1).optional().describe("Filtra por munic\xEDpio (busca parcial)."),
    min_severity: z5.number().int().min(1).max(5).optional().describe("Severidade m\xEDnima."),
    limit: z5.number().int().min(1).max(100).optional().describe("M\xE1ximo de registros (padr\xE3o 30).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ status, municipality, min_severity, limit }, ctx) => {
    if (!ctx.isAuthenticated()) return notAuthenticated();
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("strategic_alerts").select(
      "id,type,title,description,recommendation,severity,score,status,municipality,macroregion_id,risk_index,opportunity_index,created_at"
    ).order("severity", { ascending: false }).order("created_at", { ascending: false }).limit(limit ?? 30);
    if (status) query = query.eq("status", status);
    if (municipality) query = query.ilike("municipality", `%${municipality}%`);
    if (typeof min_severity === "number") query = query.gte("severity", min_severity);
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { alerts: data ?? [] }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "sumdjlmjtqgfzkcfkceq";
var mcp_default = defineMcp({
  name: "gestao-eleitoral",
  title: "Gest\xE3o Eleitoral",
  version: "0.1.0",
  instructions: "Ferramentas da plataforma de intelig\xEAncia eleitoral Politiza IA. Permite consultar candidatos, a\xE7\xF5es de campo, lideran\xE7as municipais, ativos pol\xEDticos e alertas estrat\xE9gicos. Todos os dados respeitam as permiss\xF5es do usu\xE1rio conectado.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [
    list_candidates_default,
    list_actions_default,
    list_leaders_default,
    list_political_assets_default,
    list_strategic_alerts_default
  ]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.28.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
